name: Model Validate and Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-build:
    uses: CBIIT/bento-workflows/.github/workflows/model-test-and-deploy.yml@v1.1.4.5
    with:
      model_files: |
        cds-model.yml cds-model-props.yml
      model_prefix: cds-model
      event_name: ${{ github.event_name }}
