name: Model Validate and Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-and-build:
    permissions:
      packages: read
      contents: write
    uses: CBIIT/bento-workflows/.github/workflows/model-test-and-deploy.yml@v2.3.12
    with:
      model_files: |
        cds-model.yml cds-model-props.yml
      model_prefix: cds-model
      event_name: ${{ github.event_name }}
      nodes_only_graph: yes
    secrets:
      token: ${{ secrets.PAT }}

